[package]
name = "noodle-io"
description = "Audio and MIDI device I/O, audio file decoding and disk streaming."
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cpal = "0.18.2"
hound = "3.5.1"
noodle-engine.workspace = true

[dev-dependencies]
noodle-core.workspace = true
